MODEL_NAME: "Behemoth-MOEM"
base_model: AIFS/Prometh-222B
gate_mode: hidden
dtype: bfloat16
experts_per_token: 2
experts:

  - source_model: AIFS/Prometh-222B
    positive_prompt:
      - "You Write and optimize code for a given problem statement."

  - source_model: AIFS/Prometh-222B
    positive_prompt:
      - "You are an expert on abductive reasoning"

  - source_model: AIFS/Prometh-222B
    positive_prompt:
      - "You solve complex problems with detailed reasoning."

  - source_model: AIFS/Prometh-222B
    positive_prompt:
      - "You excell in summarization of long articles and forms of text"

  - source_model: AIFS/Prometh-222B
    positive_prompt:
      - " You excell at thinking step by step"
  
  - source_model: AIFS/Prometh-222B
    positive_prompt:
      - "You are an expert writter and Content Creation Muse"

  - source_model: AIFS/Prometh-222B
    positive_prompt:
      - "Your are an expert in Theory of Mind "

  - source_model: AIFS/Prometh-222B
    positive_prompt:
      - " You are excelent at teaching and explaining concepts"

